{
    "0": "Moon Sign \"Lunatic Rain\"",
    "4": "Moon Sign \"Luna Cyclone\"",
    "8": "Shooting Star \"Petit Comet\"",
    "12": "Stardust \"Sprinkle Piece\"",
    "16": "Star Sign \"Twinkle Sapphire\"",
    "20": "Sunlight \"Sunshine Blast\"",
    "24": "Light Sign \"Rutile Flection\"",
    "28": "Sunfire \"Ice Dissolver\"",
    "32": "Sky Sign \"Elfin Canopy\"",
    "36": "Band Tech \"Three Cords At Midnight\"",
    "40": "\"Tsukumogami Band\"",
    "44": "Rainbow Light \"Prism Flash\"",
    "48": "Light Fairy \"Diamond Ring\"",
    "52": "Light Sign \"Blue Deflection\"",
    "56": "Starlight \"Star Laser\"",
    "60": "Light Sign \"Triple Meteor\"",
    "64": "Starfire \"Ice Dissolver\"",
    "68": "Bright Star \"Orion Belt\"",
    "72": "Band Tech \"Three Cords At Midnight\"",
    "76": "\"Tsukumogami Band\"",
    "80": "Sun Sign \"Aggressive Light\"",
    "84": "Sun Sign \"Direct Sunlight\"",
    "88": "Shooting Star \"Comet Stream\"",
    "92": "Stardust \"Star Piece Shower\"",
    "96": "Star Sign \"Shooting Sapphire\"",
    "100": "Moonlight \"Silent Storm\"",
    "104": "Light Sign \"Bright Night\"",
    "108": "Moonfire \"Ice Dissolver\"",
    "112": "Sky Sign \"Break Canopy\"",
    "116": "Band Tech \"Three Cords At Midnight\"",
    "120": "\"Tsukumogami Band\"",
    "124": "Moonlight \"Dark Stillness\"",
    "128": "Hindering Light \"Moonlight Wall\"",
    "132": "Night Sign \"Night Fairies\"",
    "136": "Starlight \"Star Storm\"",
    "140": "Light Sign \"Extensive Meteor\"",
    "144": "Starfire \"Ice Dissolver\"",
    "148": "Bright Star \"Great Triangle\"",
    "152": "Band Tech \"Three Cords At Midnight\"",
    "156": "\"Tsukumogami Band\"",
    "160": "Star Sign \"Starlight Rain\"",
    "164": "Star Sign \"Red Star\"",
    "168": "Flickering Light \"Fatal Flash\"",
    "172": "Light Fairy \"Cross Diffusion\"",
    "176": "Light Sign \"Yellow Deflection\"",
    "180": "Moonlight \"Silent Flower\"",
    "184": "Light Sign \"Full Moon Night\"",
    "188": "Moonfire \"Ice Dissolver\"",
    "192": "Falling Light \"Triple Light\"",
    "196": "Band Tech \"Three Cords At Midnight\"",
    "200": "\"Tsukumogami Band\"",
    "204": "Moonlight \"Moon Stillness\"",
    "208": "Light Barrier \"Wall Break\"",
    "212": "Moonlight \"Silent Cyclone\"",
    "216": "Sunlight \"Sunshine Needle\"",
    "220": "Light Sign \"Hyper Inflection\"",
    "224": "Sunfire \"Ice Dissolver\"",
    "228": "Violent Light \"Sunburst\"",
    "232": "Band Tech \"Three Cords At Midnight\"",
    "236": "\"Tsukumogami Band\"",
    "240": "Light Sign \"Mysterious Beam\"",
    "241": "Light Blast \"Shoot the Little Moon\"",
    "242": "Magic Bullet \"Test Slave\"",
    "243": "Closure Sign \"Big Crunch\"",
    "244": "Hate Sign \"Spinning Beam\"",
    "245": "Unsealed Magic \"Open Universe\"",
    "246": "Magic Cross \"Grand Cross\"",
    "247": "Shooting Star \"Super Perseid\"",
    "248": "\"Blazing Star-like Tag\"",
    "249": "\"Beam Of Revolution\""
}