{
    "0": "Symbol \"Dance of the Dead Butterflies\"",
    "2": "Symbol \"Dance of the Dead Butterflies - Cherry Blossoms -\"",
    "4": "Ghostly Butterfly \"Ghost Spot\"",
    "6": "Ghostly Butterfly \"Ghost Spot - Cherry Blossoms -\"",
    "8": "Nether Sign \"Endless Evening Cherry Blossoms\"",
    "12": "Cherry Blossom Sign \"Saigyou Cherry Blossom Blizzard\"",
    "14": "Echo Sign \"Mountain Echo\"",
    "16": "Echo Sign \"Mountain Echo Scramble\"",
    "18": "Echo Sign \"Power Resonance\"",
    "22": "Mountain Echo \"Long-Range Echo\"",
    "24": "Mountain Echo \"Amplify Echo\"",
    "26": "Great Voice \"Charged Cry\"",
    "28": "Great Voice \"Charged Yahoo!\"",
    "30": "Rainbow Sign \"Umbrella Cyclone\"",
    "32": "Recovery \"Heal By Desire\"",
    "36": "Poison Nail \"Poison Raze\"",
    "38": "Poison Nail \"Poison Murder\"",
    "40": "Desire Sign \"Saved Up Desire Spirit Invitation\"",
    "42": "Desire Spirit \"Score Desire Eater\"",
    "44": "Evil Sign \"Yang Xiaogui\"",
    "45": "Evil Sign \"Guhun Yegui\"",
    "47": "Demonify \"Zouhuo Rumo\"",
    "51": "Possession \"Corpse Tongji\"",
    "53": "Spirit Link \"Tongling Yoshika\"",
    "55": "Path Sign \"Tao Fomenting\"",
    "59": "Thunder Arrow \"Gagouji's Cyclone\"",
    "60": "Thunder Arrow \"Gagouji's Cyclone\"",
    "61": "Thunder Arrow \"Gagouji's Tornado\"",
    "62": "Heaven Sign \"Rainy Iwafune\"",
    "64": "Heaven Sign \"Iwafune Ascending to Heaven\"",
    "66": "Throwing Dishes \"Mononobe's Eighty Sake Cups\"",
    "70": "Blaze Sign \"Blazing Winds of Haibutsu\"",
    "72": "Blaze Sign \"Sakuraiji in Flames\"",
    "74": "Saint Girl \"Oomonoimi's Dinner\"",
    "78": "Honor \"Colors of Twelve Levels\"",
    "80": "Honor \"Ranks of Twelve Levels\"",
    "82": "Hermit Sign \"Taoist of the Land of the Rising Sun\"",
    "84": "Hermit Sign \"Emperor of the Land of the Rising Sun\"",
    "86": "Summon \"Royal Clan's Chaotic Dance\"",
    "90": "Secret Treasure \"Armillary Sphere of Ikaruga-dera\"",
    "93": "Secret Treasure \"Prince Shotoku's Out-of-Place Artifact\"",
    "94": "Light Sign \"Halo of the Guse Kannon\"",
    "96": "Light Sign \"Guse Flash\"",
    "98": "Discernment \"Laser of Seventeen Articles\"",
    "100": "Divine Light \"Honor the Avoidance of Defiance\"",
    "102": "\"Falling Stars on Divine Spirit Mausoleum\"",
    "104": "\"Newborn Divine Spirit\"",
    "106": "Unknown \"Will-o'-wisps in Unknown Orbit\"",
    "107": "Unknown \"Skyfish with Unknown Shape\"",
    "108": "Unknown \"Youkai Orb of Unknown Mechanics\"",
    "109": "First Duel \"Primate Danmaku Transformation\"",
    "110": "Second Duel \"Carnivorous Danmaku Transformation\"",
    "111": "Third Duel \"Avian Danmaku Transformation\"",
    "112": "Fourth Duel \"Amphibian Danmaku Transformation\"",
    "113": "Fifth Duel \"Scrolls of Frolicking Animals\"",
    "114": "Sixth Duel \"Tanuki's Monstrous School\"",
    "115": "Seventh Duel \"Wild Deserted Island\"",
    "116": "Transformation \"Pseudo-Exorcism of the Stupid Shrine Maiden\"",
    "117": "\"Mamizou Danmaku in Ten Transformations\"",
    "118": "Raccoon Sign \"Full Moon Pompokolin\"",
    "119": "Cherry Blossom Sign \"Cherry Blossom Blizzard Hell\"",
    "120": "Mountain Echo \"Yamabiko's Specialty Echo Demonstration\"",
    "121": "Poison Nail \"Undead Murderer\"",
    "122": "Path Sign \"TAO Fetal Movement ~Dao~\"",
    "123": "Vengeful Spirit \"Iruka's Thunder\"",
    "124": "Saint Girl \"Sun Goddess's Sacrifice\"",
    "125": "\"Divine Spirits' Universe\"",
    "126": "\"Wild Carpet\""
}